spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/easy_order

  profiles:
    active: prod, test

jwt:
  secret:
    key: 3F4428472B4B6150645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A462D4A614E645267556A586E3272357538
  expiry:
    in:
     minutes: 10

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080

